version: '3.8'

services:
  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - 8022:8000
    depends_on:
        - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
    ports:
      - 5432:5432